# Generated by Django 5.0.1 on 2024-02-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_alter_finance_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_info',
            name='Category',
            field=models.CharField(choices=[('BILLS', 'Bills'), ('RENT', 'Rent'), ('FOOD', 'Food'), ('EDUCATION', 'Education'), ('MISC', 'Misc'), ('TRAVEL', 'Travel')], default='BILLS', max_length=10),
        ),
    ]
